version: '3'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - '5432:5432'
    restart: always
    command:
      - docker rm -f postgres-db 2>/dev/null || true
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    restart: always
    command:
      - docker rm -f redis 2>/dev/null || true
      - redis-server --requirepass docker